# Generated by Django 4.0.2 on 2022-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='usuario/perfil/', verbose_name='Imagen de perfil'),
        ),
    ]
